### ISSUE TITLE
Error in Table "32/64-bit ModR/M Byte"

### ISSUE THREAD

**Issue by d0sboots** [Barebit/x86reference#10]
In the Table "32/64-bit ModR/M Byte", for Mod=00, R/M=001 the effective address is listed as "[RCX/EDX]+disp8". This is incorrect, it should be "[RCX/ECX]+disp8". (I.e. with 32-bit operands the base register remains ECX.)

This is verified both by the correct listing in the table below, "32-bit ModR/M Byte", as well as Intel's official manual.

**Comment by BarebitOpenSource** [comment]
Thank you for spotting it, it's a typo. It takes some time to fix it.

Relevant link: http://ref.x86asm.net/coder64.html#modrm_byte_32_64

**Comment by BarebitOpenSource** [comment]
Moved to https://github.com/mazegen/x86reference/issues/17
