### ISSUE TITLE
SIB Notes are wrong/misleading

### ISSUE THREAD

**Issue by d0sboots** [Barebit/x86reference#15]
The mini-tables at http://ref.x86asm.net/coder.html#sib64_base_101 are very misleading. It claims, for instance, that with no REX.X and mod bits=01, the scaled index base="RBP/EBP+disp8". However, with mod bits=01, the offset of +disp8 is already accounted for in the table "32/64-bit ModR/M Byte", under Effective Address (which must be "[sib]+disp8" in this case).

This gives the impression that the offset is added **twice** (or maybe there are two offsets?), when this is not the case. The base should be listed as simply "RBP/EBP", to match the other bases in the table "32/64-bit SIB Byte" (which don't have the offset added, because it's accounted for in the original ModR/M calculation).

The same goes for the bits=02 case, and the table at http://ref.x86asm.net/coder.html#sib32_base_101.

**Comment by BarebitOpenSource** [comment]
This is how it is indicated in the Intel manual and also on [Sandpile](https://sandpile.org/x86/opc_sib.htm), I don't think it needs to be fixed.
