### ISSUE TITLE
Mov Debug register possible wrong operand type

### ISSUE THREAD

**Issue by Kashio** [Barebit/x86reference#16]
Opcode `0F 23` 
> Move to/from Debug Registers

[Entry number 2](https://github.com/Barebit/x86reference/blob/master/x86reference.xml#L7927) should the operand type be of type `d` for 32 bit and not `q` for 64 bit?
This second entry is not set with `mode="e"` which specify different behavior for x64.

**Comment by BarebitOpenSource** [comment]
Yes, this seems to be a typo. The second entry should be: `MOV Dd, Hd`. The other entries are all correct.

**Comment by BarebitOpenSource** [comment]
Fixed.
