### ISSUE TITLE
[Enhancement] Add JSON reference file

### ISSUE THREAD

**Issue by deeprobin** [Barebit/x86reference#20]

**Comment by arizvisa** [comment]
@deeprobin, you can simply use the json-toolkit (really xmltodict from python) to convert xml to json.

the thing that sucks about json, is you don't have comments which is super important for anybody who takes on the endeavor of curating this for us. not to speak on behalf of the author, but there's version information, and a number of other things that are important as you need to keep in mind that this was hand-made.

**Comment by BarebitOpenSource** [comment]
This could be done by transforming the XML to JSON but it is not planned.
