### ISSUE TITLE
Missing Bit Manipulation Instruction Sets: ABM, BMI1, BMI2, and TBM

### ISSUE THREAD

**Issue by xelxebar** [Barebit/x86reference#21]
Just recently having learned about the various [Bit Manipulation Instruction Sets][0], I happened to notice their conspicuous lack on the x86reference. Is this intentional for some reason, or would it be worth a PR?

[0]:https://en.wikipedia.org/wiki/Bit_Manipulation_Instruction_Sets

**Comment by BarebitOpenSource** [comment]
`POPCNT` is already there. `LZCNT` should be added.

BMI1, BMI2, and TBM are VEX-ecoded instructions and VEX encoding is yet to be implemented.

**Comment by BarebitOpenSource** [comment]
```
TZCNT — Count the Number of Trailing Zero Bits

F3 0F BC /r       TZCNT r16, r/m16
F3 0F BC /r       TZCNT r32, r/m32
F3 REX.W 0F BC /r TZCNT r64, r/m64

TZCNT Gv, Ev

CPU feature: BMI1
```

**Comment by BarebitOpenSource** [comment]
Added `LZCNT` that is not part of BMI1.

**Comment by BarebitOpenSource** [comment]
Added `TZCNT`. It's part of BMI1 but the only non-VEX instruction. The rest of the BMI instructions will be added along with all the other VEX instructons.
