### ISSUE TITLE
MOVSD use wrong operand types

### ISSUE THREAD

**Issue by Kashio** [Barebit/x86reference#22]
Right now `MOVSD` encoded with opcode `F2 0F 10` or `F2 0F 11` use operand type `sd`  for its operand of addressing `W` which is defined as:

> Scalar element of a 128-bit packed double-precision floating data.

According to the intel docs:

> Moves a scalar double-precision floating-point value from the source operand (second operand) to the destination operand (first operand). The source and destination operands can be XMM registers or 64-bit memory locations. This instruction can be used to move a double-precision floating-point value to and from the low quadword of an XMM register and a 64-bit memory location, or to move a double-precision floating-point value between the low quadwords of two XMM registers. The instruction cannot be used to transfer data between memory locations.

Since it's only copying the lower 64 bits of the register and the memory variant is also referencing 64 bit memory the operand type should be of type `q` which is defined as:

> Quadword, regardless of operand-size attribute (for example, CALL ([FF /2](http://ref.x86asm.net/geek.html#xFF_2))).

**Comment by BarebitOpenSource** [comment]
Thanks for your review, however, the type `q` means 64-bit **integer** while `MOVSD` operates on scalar (64-bit) element of a 128-bit packed double-precision floating data. In both cases the size is always 64 bits but the data type differs. Also the Intel manual indicates `sd` all the time.

Let me know if I'm missing something.

**Comment by BarebitOpenSource** [comment]
Feel free to reopen this issue if you still think the operand type is wrong.
