### ISSUE TITLE
MOVSLDUP use wrong operand types

### ISSUE THREAD

**Issue by Kashio** [Barebit/x86reference#24]
Right now `MOVSLDUP ` encoded with opcode `F3 0F 12` use operand type `q`  for both its operands which is defined as:

> Quadword, regardless of operand-size attribute (for example, CALL (FF /2)).

According to the intel docs:

> Duplicates even-indexed single-precision floating-point values from the source operand (the second operand). See [Figure 4-4](https://www.felixcloutier.com/x86/MOVSLDUP.html#fig-4-4). The source operand is an XMM, YMM or ZMM register or 128, 256 or 512-bit memory location and the destination operand is an XMM, YMM or ZMM register.

Putting aside VEX/EVEX, the instruction is dealing with 128 bit single precision fp values for both its operands, the operand type should be of type `ps` which is defined as:

> 128-bit packed single-precision floating-point data.

**Comment by BarebitOpenSource** [comment]
Good point. I need to figure out why Intel uses this operand type in the manual.

**Comment by BarebitOpenSource** [comment]
Won't fix, see #27.
