### ISSUE TITLE
UCOMISD use wrong operand types

### ISSUE THREAD

**Issue by Kashio** [Barebit/x86reference#33]
Right now `UCOMISD` encoded with opcode ~`66 F2 0F 2E`~ `66 0F 2E` use operand type `sd`  for its operand of addressing `W` which is defined as:

> Scalar element of a 128-bit packed double-precision floating data.

According to the intel docs:

> Performs an unordered compare of the double-precision floating-point values in the low quadwords of operand 1 (first operand) and operand 2 (second operand), and sets the ZF, PF, and CF flags in the EFLAGS register according to the result (unordered, greater than, less than, or equal). The OF, SF and AF flags in the EFLAGS register are set to 0. The unordered result is returned if either source operand is a NaN (QNaN or SNaN).
> Operand 1 is an XMM register; operand 2 can be an XMM register or a 64 bit memory

Since it's only copying the lower 64 bits of the register and the memory variant is also referencing 64bit memory the operand type should be of type `q` which is defined as:

> Quadword, regardless of operand-size attribute (for example, CALL ([FF /2](http://ref.x86asm.net/geek.html#xFF_2))).

**Comment by BarebitOpenSource** [comment]
This one looks right. Refer to #22.

**Comment by BarebitOpenSource** [comment]
Feel free to reopen this issue if you still think the operand type is wrong.
