### ISSUE TITLE
PEXTRQ not specified for 64 bit mode

### ISSUE THREAD

**Issue by Kashio** [Barebit/x86reference#34]
Right now `PEXTRQ` entry isn't specified with the `mode="e"` attribute for 64 bit mode.

>  PEXTRQ is not encodable in non-64-bit modes and requires REX.W in 64-bit mode.

We need to add another separate entry with the `mode="e"` attribute for 64 bit mode for it.

**Comment by BarebitOpenSource** [comment]
Good catch.

**Comment by BarebitOpenSource** [comment]
Fixed.
