### ISSUE TITLE
ROUNDSS use wrong operand types

### ISSUE THREAD

**Issue by Kashio** [Barebit/x86reference#35]
Right now `ROUNDSS` encoded with opcode `66 0F 3A 0A` use operand type `ss`  for its operand of addressing `W` which is defined as:

> Scalar element of a 128-bit packed single-precision floating data.

According to the intel docs:

> Round the single-precision floating-point value in the lowest dword of the source operand (second operand) using the rounding mode specified in the immediate operand (third operand) and place the result in the destination operand (first operand).

Since it's only copying the lower 32 bits of the register and the memory variant is also referencing 32 bit memory the operand type should be of type `d` which is defined as:

> Doubleword, regardless of operand-size attribute.

**Comment by BarebitOpenSource** [comment]
This one looks right. Refer to #23.

**Comment by BarebitOpenSource** [comment]
Feel free to reopen this issue if you still think the operand type is wrong.
