### ISSUE TITLE
ROUNDSD use wrong operand types

### ISSUE THREAD

**Issue by Kashio** [Barebit/x86reference#36]
Right now `ROUNDSD` encoded with opcode `66 0F 3A 0B` use operand type `sd`  for its operand of addressing `W` which is defined as:

> Scalar element of a 128-bit packed single-precision floating data.

According to the intel docs:

> Round the DP FP value in the lower qword of the source operand (second operand) using the rounding mode specified in the immediate operand (third operand) and place the result in the destination operand (first operand). 

Since it's only copying the lower 64 bits of the register and the memory variant is also referencing 64 bit memory the operand type should be of type `q` which is defined as:

> Quadword, regardless of operand-size attribute (for example, CALL ([FF /2](http://ref.x86asm.net/geek.html#xFF_2))).

**Comment by BarebitOpenSource** [comment]
This one looks right. Refer to #22.

**Comment by BarebitOpenSource** [comment]
Feel free to reopen this issue if you still think the operand type is wrong.
