### ISSUE TITLE
SQRTSD use wrong operand types

### ISSUE THREAD

**Issue by Kashio** [Barebit/x86reference#38]
Right now `SQRTSD` encoded with opcode `F2 0F 51` use operand type `sd`  for its operand of addressing `W` which is defined as:

> Scalar element of a 128-bit packed double-precision floating data.

According to the intel docs:

> Computes the square root of the low double-precision floating-point value in the second source operand and stores the double-precision floating-point result in the destination operand. The second source operand can be an XMM register or a 64-bit memory location. The first source and destination operands are XMM registers.

Since it's only operate on the lower 64 bits of the register and the memory variant is also referencing 64 bit memory the operand type should be of type `q` which is defined as:

> Quadword, regardless of operand-size attribute (for example, CALL ([FF /2](http://ref.x86asm.net/geek.html#xFF_2))).

**Comment by BarebitOpenSource** [comment]
This one looks right. Refer to #22.

**Comment by BarebitOpenSource** [comment]
Feel free to reopen this issue if you still think the operand type is wrong.
