### ISSUE TITLE
JMP use wrong operand type

### ISSUE THREAD

**Issue by Kashio** [Barebit/x86reference#43]
Right now `JMP` encoded with opcodes `EB` use operand type `bs` for its operand of addressing `J` which is defined as:

> Byte, sign-extended to the size of the destination operand.

The problem is that the immediate is always sign extended to the size of the stack pointer. Therefore the most appropriate operand type for these should be `bss`:

> Byte, sign-extended to the size of the stack pointer (for example, PUSH ([6A](http://ref.x86asm.net/geek.html#x6A))).

**Comment by BarebitOpenSource** [comment]
Hello, I'm sorry for not being responsive. Thank you for your review.

The `Jbs` actually reads as: "Relative offset to be added to the IP register. The relative offset is sign-extended to the size of of the IP register."

I think you are confused by the `bs` being "Byte, sign-extended to the size of the destination operand.". The destination operand is determined by `J` addressing so it is either IP, EIP or RIP.

**Comment by Kashio** [comment]
Hey, I see what you mean, maybe a better solution would be to add to all such instructions:
```json
  "dst": [
    {
      "_address": "??",
      "_displayed": "no",
      "__text": "[rIP]"
    }
  ],
```

Since `bs` is not an official operand type according to the docs and the interpretation of

> Byte, sign-extended to the size of the **destination operand**.

is confusing if no destination operand is mentioned in the instruction, although the `J` addressing implies it I think it would be better to add it since it is more semantically correct as per the description, what do you think?

**Comment by BarebitOpenSource** [comment]
Good point. It seems that all what needs to be done is to correct the description of `bs` to "Byte, sign-extended to the size of the ~destination~ operand."

Well, the `J` addressing is tricky. To make it completely correct, it should be a destination operand but it would make the byte value also the destination and that doesn't make much sense. This would need to be solved by introducing new types of operands but I don't think it's worth it.

**Comment by BarebitOpenSource** [comment]
Added to the main README but ref.x86asm.net needs to fixed.

**Comment by BarebitOpenSource** [comment]
Moved to https://github.com/mazegen/x86reference/issues/9
