### ISSUE TITLE
INTO is invalid in 64 bit mode

### ISSUE THREAD

**Issue by Kashio** [Barebit/x86reference#45]
Right now `INTO` encoded with opcode `CE` has a missing entry for 64 bit mode which is invalid according to the manual:

![325383-sdm-vol-2abcd pdf (SECURED) - Adobe Acrobat Reader (64-bit)](https://user-images.githubusercontent.com/16501683/233846005-318f3373-aa9f-4243-8ae2-462453813e8f.jpg)

**Comment by BarebitOpenSource** [comment]
Good catch.

**Comment by BarebitOpenSource** [comment]
Fixed.
