### ISSUE TITLE
CMPSD use wrong operand types

### ISSUE THREAD

**Issue by Kashio** [Barebit/x86reference#49]
Right now `CMPSD` encoded with opcode `F2 0F C2` use operand type `sd`  for its operand of addressing `W` which is defined as:

> Scalar element of a 128-bit packed double-precision floating data.

According to the intel docs:

> Compare low double-precision floating-point value in
> xmm2/m64 and xmm1 using bits 2:0 of imm8 as comparison
> predicate.

Since it's only comparing the lower 64 bits of the register and the memory variant is also referencing 64 bit memory the operand type should be of type `q` which is defined as:

> Quadword, regardless of operand-size attribute (for example, CALL ([FF /2](http://ref.x86asm.net/geek.html#xFF_2))).

**Comment by BarebitOpenSource** [comment]
This one looks right. Refer to #22.

**Comment by BarebitOpenSource** [comment]
Feel free to reopen this issue if you still think the operand type is wrong.
