### ISSUE TITLE
Add missing instruction CLFLUSHOPT

### ISSUE THREAD

**Issue by Kashio** [Barebit/x86reference#53]
`CLFLUSHOPT` encoded as `NFx 66 0F AE /7 CLFLUSHOPT m8` needs to be added.

**Comment by BarebitOpenSource** [comment]
Yes. Note that this comes with its own CPUID feature flag `CLFLUSHOPT`.

**Comment by BarebitOpenSource** [comment]
Also:

    CLDEMOTE
    CLWB

**Comment by BarebitOpenSource** [comment]
Moved to https://github.com/mazegen/x86reference/issues/7
